<a href="https://colab.research.google.com/github/nmeedg/data_learning/blob/main/bibliotheque%20_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Bibliotheque Numpy**

In [ ]:
import numpy as np
liste=range(1,200)
liste=np.array(liste)
print(type(liste))
print(max(liste))
print(liste.dtype)
b=sum(liste)/len(liste)
# testliste=np.ones(10)
testliste=np.linspace(-1,1,100)
print(testliste.dtype)
print(testliste)
# print(np.mean(liste))
# print(b)

<class 'numpy.ndarray'>
199
int64
float64
[-1.         -0.97979798 -0.95959596 -0.93939394 -0.91919192 -0.8989899
 -0.87878788 -0.85858586 -0.83838384 -0.81818182 -0.7979798  -0.77777778
 -0.75757576 -0.73737374 -0.71717172 -0.6969697  -0.67676768 -0.65656566
 -0.63636364 -0.61616162 -0.5959596  -0.57575758 -0.55555556 -0.53535354
 -0.51515152 -0.49494949 -0.47474747 -0.45454545 -0.43434343 -0.41414141
 -0.39393939 -0.37373737 -0.35353535 -0.33333333 -0.31313131 -0.29292929
 -0.27272727 -0.25252525 -0.23232323 -0.21212121 -0.19191919 -0.17171717
 -0.15151515 -0.13131313 -0.11111111 -0.09090909 -0.07070707 -0.05050505
 -0.03030303 -0.01010101  0.01010101  0.03030303  0.05050505  0.07070707
  0.09090909  0.11111111  0.13131313  0.15151515  0.17171717  0.19191919
  0.21212121  0.23232323  0.25252525  0.27272727  0.29292929  0.31313131
  0.33333333  0.35353535  0.37373737  0.39393939  0.41414141  0.43434343
  0.45454545  0.47474747  0.49494949  0.51515152  0.53535354  0.55555556
  0.575757

In [ ]:
# print(testliste[:6])
# print(testliste[-3:])
# print(testliste[::2])
# print(testliste[::-1])
# print(testliste[testliste > 0.5])
testliste[testliste > 0.5]=0
print(testliste.shape)
# print(max(testliste))

print(testliste.argmax())
testliste

(100,)
74


array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182,
       -0.7979798 , -0.77777778, -0.75757576, -0.73737374, -0.71717172,
       -0.6969697 , -0.67676768, -0.65656566, -0.63636364, -0.61616162,
       -0.5959596 , -0.57575758, -0.55555556, -0.53535354, -0.51515152,
       -0.49494949, -0.47474747, -0.45454545, -0.43434343, -0.41414141,
       -0.39393939, -0.37373737, -0.35353535, -0.33333333, -0.31313131,
       -0.29292929, -0.27272727, -0.25252525, -0.23232323, -0.21212121,
       -0.19191919, -0.17171717, -0.15151515, -0.13131313, -0.11111111,
       -0.09090909, -0.07070707, -0.05050505, -0.03030303, -0.01010101,
        0.01010101,  0.03030303,  0.05050505,  0.07070707,  0.09090909,
        0.11111111,  0.13131313,  0.15151515,  0.17171717,  0.19191919,
        0.21212121,  0.23232323,  0.25252525,  0.27272727,  0.29292929,
        0.31313131,  0.33333333,  0.35353535,  0.37373737,  0.39

In [ ]:
maliste=[1800,1500,2000,3000,2172,5000,1400,1200,1100,1300]
revenus=np.array(maliste)
haut_revenus=revenus[revenus >= 3000]
somme=np.sum(revenus)
moyenne=np.mean(revenus)
revenus[revenus == 1400] += 200
display(revenus)
print(moyenne,somme,haut_revenus)

array([1800, 1500, 2000, 3000, 2172, 5000, 1600, 1200, 1100, 1300])

2047.2 20472 [3000 5000]


In [ ]:
multidimliste=[
    [1,2,3],
    [4,5,6]
]
multilistnumpy=np.array(multidimliste)
testtable=np.random.randint(1,8,(2,3))
display(testtable)

array([[1, 7, 2],
       [6, 4, 1]])

In [ ]:
a=np.array(
   [ [1,2],
    [3,4]]
)
b=np.array(
    [[5,10],
    [15,20]]
)
c=np.array(
    [[2,4,6],
     [3,13,22],
    [8,10,12]]
)
# print(a@b)
# print(a.dot(b))
a
# print(a.T)
a[0,1]=10
# c[:2,-2:]
print(c[:,1])
c[c[:,1] > 8]
np.vstack((c,(1,3,5)))

[ 4 13 10]


array([[ 2,  4,  6],
       [ 3, 13, 22],
       [ 8, 10, 12],
       [ 1,  3,  5]])

# **Pandas Library**